[package]
name = "handshake"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.3"
hkdf = "0.12.3"
p256 = { version = "0.13.2", features = ["ecdh", "ecdsa-core"] }
rand_core = "0.6.4"
sha2 = "0.10.7"
thiserror = "1.0.43"
tungstenite = "0.19.0"
url = "2.4.0"
